version: '3'
services:
  # Javaの設定情報
  java:
    # コンテナ名
    container_name: spring
    build: ./java
    ports:
     - "8080:8080"
    # local参照先:コンテナ展開先
    volumes:
    - ./build/libs:/app
    # コンテナ内のディレクトリ定義
    working_dir: /app
    tty: true
